name: sentinel2-gee
channels:
  - conda-forge
  - defaults
dependencies:
  # Core dependencies
  - python=3.9
  - earthengine-api>=0.1.328
  - geopandas>=0.12.0
  - xarray>=2023.1.0
  - rioxarray>=0.13.0  # Required for xarray<->rasterio integration

  # Supporting libraries
  - pandas>=1.5.0
  - numpy>=1.23.0
  - netcdf4>=1.6.0  # For NetCDF file handling
  - dask>=2023.1.0  # Used by xarray for parallel processing
  - gdal>=3.5.0  # Geospatial data processing

  # Parallel processing
  - concurrent-log-handler>=0.9.20  # Better logging for parallel ops

  # Visualization (optional)
  - matplotlib>=3.6.0
  - cartopy>=0.21.0

  # Development tools
  - pip>=22.3.0